### ISSUE TITLE
在当前目录执行：tail -F ./oracle.log 出现 'jq: command not found ErrorCode = '

### ISSUE THREAD

**Issue by jackom** [angelsky11/create-oracle-instance-script#1]
在当前目录执行：tail -F ./oracle.log 出现: 
/root/create_oracle_instance.sh: line 58:  jq: command not found
INSTANCE CREATED FAILED
/root/create_oracle_instance.sh: line 58:  jq: command not found
ErrorCode=
/root/create_oracle_instance.sh: line 58:  jq: command not found
ErrorMessage=

这个是什么原因导致的吗？希望抽空解答下，谢谢！我这边按照教程配置了oci、也安装了jq和下载了脚本等。

**Comment by angelsky11** [comment]
jq没有装好，或者是因为crontab的运行path与系统不一致，请自行google解决

**Comment by jackom** [comment]
我重新按照步骤安装了，再次执行 tail -F /root/oracle_create.log 命令，出现这个：
<img width="472" alt="image" src="https://user-images.githubusercontent.com/5052960/128624833-1fa3b0e5-b08f-4a81-9e56-b8fda6a2f5a2.png">

打印的 ErrorCode,ErrorMessage还是为空的，但是通过 ./create_oracle_instance.sh 能显示内容：
<img width="527" alt="image" src="https://user-images.githubusercontent.com/5052960/128624888-c9fec8b8-8c18-4911-9ec6-731caad9429f.png">

我的当前目录是/root。 而且在当前目前输入： jq --help，是有内容输出的。
<img width="481" alt="image" src="https://user-images.githubusercontent.com/5052960/128624952-2eb29e06-2ac1-4b47-8720-da3facd34ecb.png">


希望楼主可以帮忙看下，google了没找到解决方案。主要需求是：ErrorCode、ErrorMessage在执行 tail -F /root/oracle_create.log 命令后，能正确输出错误内容，万分感谢！
