### ISSUE TITLE
我重新按照步骤安装了，再次执行 tail -F /root/oracle_create.log 命令，打印的 ErrorCode,ErrorMessage还是为空

### ISSUE THREAD

**Issue by jackom** [angelsky11/create-oracle-instance-script#2]
我重新按照步骤安装了，再次执行 tail -F /root/oracle_create.log 命令，出现这个：
<img width="472" alt="image" src="https://user-images.githubusercontent.com/5052960/128624833-1fa3b0e5-b08f-4a81-9e56-b8fda6a2f5a2.png">

打印的 ErrorCode,ErrorMessage还是为空的，但是通过 ./create_oracle_instance.sh 能显示内容：
<img width="527" alt="image" src="https://user-images.githubusercontent.com/5052960/128624888-c9fec8b8-8c18-4911-9ec6-731caad9429f.png">

我的当前目录是/root。 而且在当前目前输入： jq --help，是有内容输出的。
<img width="481" alt="image" src="https://user-images.githubusercontent.com/5052960/128624952-2eb29e06-2ac1-4b47-8720-da3facd34ecb.png">

希望楼主可以帮忙看下，google了没找到解决方案。主要需求是：ErrorCode、ErrorMessage在执行 tail -F /root/oracle_create.log 命令后，能正确输出错误内容，万分感谢！

_Originally posted by @jackom in https://github.com/angelsky11/create-oracle-instance-script/issues/1#issuecomment-894758105_

**Comment by angelsky11** [comment]
不是说了么，是因为crontab的环境变量和系统的不一致导致的，需要在crontab里指定一下环境变量path的，google一下"crontab  环境变量"

**Comment by jackom** [comment]
<img width="482" alt="image" src="https://user-images.githubusercontent.com/5052960/128627539-addf550e-4891-4741-9277-8e55e3d2e7ac.png">

我改了执行方式：*/2 * * * * **./etc/profile;/bin/sh** /root/create_oracle_instance.sh >> /root/oracle_create.log 2>&1

黑色字体是新增的，现在还是有问题。。 新增了：./etc/profile;/bin/sh 

我的墙外机器是ubuntu 20系统的。

**Comment by angelsky11** [comment]
因为你就没有改对

https://blog.csdn.net/weixin_36343850/article/details/79217611

**Comment by jackom** [comment]
<img width="786" alt="image" src="https://user-images.githubusercontent.com/5052960/128628925-02ed7623-86dc-4ed3-b2b2-95516ecc113f.png">

wo我设置了这两个，还是不行的，囧。。搞了一下午了，。。
